### ISSUE TITLE
Mongo connection failure

### ISSUE THREAD

**Issue by dragoon** [marcofognog/heroku-mongo-sync#11]
Hello, I am experiencing the following error after a first installation of the plugin.

Heroku client internal error.
uninitialized constant Mongo::ConnectionFailure

    /Users/dragoon/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:106:in `rescue in make_connection'
    /Users/dragoon/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:102:in `make_connection'
    /Users/dragoon/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:28:in `transfer'
    /Users/dragoon/.heroku/plugins/heroku-mongo-sync/lib/heroku/command/mongo.rb:22:in `pull'
    /usr/local/Cellar/heroku-toolbelt/3.40.6/libexec/lib/heroku/command.rb:212:in `run'
    /usr/local/Cellar/heroku-toolbelt/3.40.6/libexec/lib/heroku/cli.rb:27:in `start'
    /usr/local/Cellar/heroku-toolbelt/3.40.6/libexec/bin/heroku:24:in `<main>'

**Comment by marcofognog** [comment]
Could you please tell us what is your environment?
Such as Ruby, Mongo and OS version.

**Comment by dragoon** [comment]
Thanks, I found the solution, it seems your plugin requires a mongo ruby gem of version 1.x, which current version is 2.x. Probably would be cool to update it.

**Comment by marcofognog** [comment]
Nice, I would gladly accept your contribution.
